/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 62
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_EQ = 3,
  anon_sym_id = 4,
  anon_sym_DOT = 5,
  sym_identifier = 6,
  anon_sym_NOT = 7,
  anon_sym_NOR = 8,
  anon_sym_OR = 9,
  sym_string = 10,
  sym__positive_integer = 11,
  sym__negative_integer = 12,
  sym_decimal = 13,
  anon_sym_yes = 14,
  anon_sym_no = 15,
  sym_comment = 16,
  anon_sym_COLON = 17,
  sym_language_identifier = 18,
  anon_sym_DQUOTE = 19,
  sym__localisation_string_content = 20,
  anon_sym_DOLLAR = 21,
  sym_source_file = 22,
  sym_content_file = 23,
  sym_localisation_file = 24,
  sym_collection = 25,
  sym_predicate = 26,
  sym_definition = 27,
  sym__primitive_definition = 28,
  sym__id_definition = 29,
  sym__composite_definition = 30,
  sym__value = 31,
  sym_member = 32,
  sym_id = 33,
  sym_id_number = 34,
  sym_logical_operator = 35,
  sym_literal = 36,
  sym_number = 37,
  sym_integer = 38,
  sym_boolean = 39,
  sym_language_localisation = 40,
  aux_sym__localisation_definitions = 41,
  sym_localisation_definition = 42,
  sym_localisation_string = 43,
  sym_interpolation = 44,
  aux_sym_content_file_repeat1 = 45,
  aux_sym_collection_repeat1 = 46,
  aux_sym_localisation_string_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_id] = "id",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [anon_sym_NOT] = "NOT",
  [anon_sym_NOR] = "NOR",
  [anon_sym_OR] = "OR",
  [sym_string] = "string",
  [sym__positive_integer] = "_positive_integer",
  [sym__negative_integer] = "_negative_integer",
  [sym_decimal] = "decimal",
  [anon_sym_yes] = "yes",
  [anon_sym_no] = "no",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [sym_language_identifier] = "language_identifier",
  [anon_sym_DQUOTE] = "\"",
  [sym__localisation_string_content] = "_localisation_string_content",
  [anon_sym_DOLLAR] = "$",
  [sym_source_file] = "source_file",
  [sym_content_file] = "content_file",
  [sym_localisation_file] = "localisation_file",
  [sym_collection] = "collection",
  [sym_predicate] = "predicate",
  [sym_definition] = "definition",
  [sym__primitive_definition] = "_primitive_definition",
  [sym__id_definition] = "_id_definition",
  [sym__composite_definition] = "_composite_definition",
  [sym__value] = "_value",
  [sym_member] = "member",
  [sym_id] = "id",
  [sym_id_number] = "id_number",
  [sym_logical_operator] = "logical_operator",
  [sym_literal] = "literal",
  [sym_number] = "number",
  [sym_integer] = "integer",
  [sym_boolean] = "boolean",
  [sym_language_localisation] = "language_localisation",
  [aux_sym__localisation_definitions] = "_localisation_definitions",
  [sym_localisation_definition] = "localisation_definition",
  [sym_localisation_string] = "localisation_string",
  [sym_interpolation] = "interpolation",
  [aux_sym_content_file_repeat1] = "content_file_repeat1",
  [aux_sym_collection_repeat1] = "collection_repeat1",
  [aux_sym_localisation_string_repeat1] = "localisation_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_id] = anon_sym_id,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_NOR] = anon_sym_NOR,
  [anon_sym_OR] = anon_sym_OR,
  [sym_string] = sym_string,
  [sym__positive_integer] = sym__positive_integer,
  [sym__negative_integer] = sym__negative_integer,
  [sym_decimal] = sym_decimal,
  [anon_sym_yes] = anon_sym_yes,
  [anon_sym_no] = anon_sym_no,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_language_identifier] = sym_language_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__localisation_string_content] = sym__localisation_string_content,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_source_file] = sym_source_file,
  [sym_content_file] = sym_content_file,
  [sym_localisation_file] = sym_localisation_file,
  [sym_collection] = sym_collection,
  [sym_predicate] = sym_predicate,
  [sym_definition] = sym_definition,
  [sym__primitive_definition] = sym__primitive_definition,
  [sym__id_definition] = sym__id_definition,
  [sym__composite_definition] = sym__composite_definition,
  [sym__value] = sym__value,
  [sym_member] = sym_member,
  [sym_id] = sym_id,
  [sym_id_number] = sym_id_number,
  [sym_logical_operator] = sym_logical_operator,
  [sym_literal] = sym_literal,
  [sym_number] = sym_number,
  [sym_integer] = sym_integer,
  [sym_boolean] = sym_boolean,
  [sym_language_localisation] = sym_language_localisation,
  [aux_sym__localisation_definitions] = aux_sym__localisation_definitions,
  [sym_localisation_definition] = sym_localisation_definition,
  [sym_localisation_string] = sym_localisation_string,
  [sym_interpolation] = sym_interpolation,
  [aux_sym_content_file_repeat1] = aux_sym_content_file_repeat1,
  [aux_sym_collection_repeat1] = aux_sym_collection_repeat1,
  [aux_sym_localisation_string_repeat1] = aux_sym_localisation_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_id] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__positive_integer] = {
    .visible = false,
    .named = true,
  },
  [sym__negative_integer] = {
    .visible = false,
    .named = true,
  },
  [sym_decimal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_yes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_no] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_language_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__localisation_string_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_content_file] = {
    .visible = true,
    .named = true,
  },
  [sym_localisation_file] = {
    .visible = true,
    .named = true,
  },
  [sym_collection] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__primitive_definition] = {
    .visible = false,
    .named = true,
  },
  [sym__id_definition] = {
    .visible = false,
    .named = true,
  },
  [sym__composite_definition] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_member] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_id_number] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_number] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_language_localisation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__localisation_definitions] = {
    .visible = false,
    .named = false,
  },
  [sym_localisation_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_localisation_string] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_content_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_collection_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_localisation_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_id_number = 1,
  field_key = 2,
  field_localisation_key = 3,
  field_localisation_string = 4,
  field_member = 5,
  field_namespace = 6,
  field_operand = 7,
  field_parent = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_id_number] = "id_number",
  [field_key] = "key",
  [field_localisation_key] = "localisation_key",
  [field_localisation_string] = "localisation_string",
  [field_member] = "member",
  [field_namespace] = "namespace",
  [field_operand] = "operand",
  [field_parent] = "parent",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [2] =
    {field_operand, 0, .inherited = true},
  [3] =
    {field_key, 0},
    {field_value, 2},
  [5] =
    {field_operand, 0},
  [6] =
    {field_id_number, 2},
    {field_namespace, 0},
  [8] =
    {field_member, 2},
    {field_parent, 0},
  [10] =
    {field_localisation_key, 0},
    {field_localisation_string, 2},
  [12] =
    {field_localisation_key, 0},
    {field_localisation_string, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 16,
  [30] = 14,
  [31] = 15,
  [32] = 18,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_literal,
  sym_number,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_literal] = {.index = 0, .length = 3},
  [sym_number] = {.index = 3, .length = 2},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_boolean,
    sym_number,
    sym_string,
  [3] =
    sym_decimal,
    sym_integer,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 45,
        '#', 42,
        '$', 48,
        '-', 10,
        '.', 19,
        ':', 43,
        '=', 17,
        'N', 20,
        'O', 21,
        'i', 24,
        'l', 23,
        'n', 26,
        'y', 25,
        '{', 15,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '$') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 5,
        '#', 42,
        '-', 10,
        'N', 20,
        'O', 21,
        'i', 24,
        'n', 26,
        'y', 25,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == 'n') ADVANCE(26);
      if (lookahead == 'y') ADVANCE(25);
      if (lookahead == '{') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == 'n') ADVANCE(8);
      if (lookahead == 'y') ADVANCE(7);
      if (lookahead == '}') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == 'N') ADVANCE(20);
      if (lookahead == 'O') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 'l') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == 'N') ADVANCE(20);
      if (lookahead == 'O') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == '}') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '#') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_id);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R') ADVANCE(31);
      if (lookahead == 'T') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(29);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_NOT);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_NOR);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_OR);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__positive_integer);
      if (lookahead == '.') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__negative_integer);
      if (lookahead == '.') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_yes);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_yes);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_no);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_no);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '"' ||
          lookahead == '$') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_language_identifier);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__localisation_string_content);
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '$') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__localisation_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 13},
  [37] = {.lex_state = 13},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 13},
  [41] = {.lex_state = 13},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 13},
  [46] = {.lex_state = 13},
  [47] = {.lex_state = 13},
  [48] = {.lex_state = 13},
  [49] = {.lex_state = 13},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 13},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_id] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_NOR] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [sym__positive_integer] = ACTIONS(1),
    [sym__negative_integer] = ACTIONS(1),
    [sym_decimal] = ACTIONS(1),
    [anon_sym_yes] = ACTIONS(1),
    [anon_sym_no] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_language_identifier] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(60),
    [sym_content_file] = STATE(61),
    [sym_localisation_file] = STATE(61),
    [sym_definition] = STATE(6),
    [sym__primitive_definition] = STATE(28),
    [sym__id_definition] = STATE(21),
    [sym__composite_definition] = STATE(12),
    [sym_logical_operator] = STATE(59),
    [sym_language_localisation] = STATE(57),
    [aux_sym_content_file_repeat1] = STATE(6),
    [anon_sym_id] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_NOT] = ACTIONS(9),
    [anon_sym_NOR] = ACTIONS(9),
    [anon_sym_OR] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_language_identifier] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_id,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      sym_string,
    ACTIONS(19), 1,
      sym_decimal,
    STATE(12), 1,
      sym__composite_definition,
    STATE(21), 1,
      sym__id_definition,
    STATE(28), 1,
      sym__primitive_definition,
    STATE(31), 1,
      sym_integer,
    STATE(59), 1,
      sym_logical_operator,
    ACTIONS(17), 2,
      sym__positive_integer,
      sym__negative_integer,
    ACTIONS(21), 2,
      anon_sym_yes,
      anon_sym_no,
    STATE(5), 2,
      sym_definition,
      aux_sym_content_file_repeat1,
    STATE(8), 2,
      sym_literal,
      aux_sym_collection_repeat1,
    STATE(29), 2,
      sym_number,
      sym_boolean,
    ACTIONS(9), 3,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [59] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_string,
    ACTIONS(31), 1,
      sym_decimal,
    STATE(15), 1,
      sym_integer,
    ACTIONS(29), 2,
      sym__positive_integer,
      sym__negative_integer,
    ACTIONS(33), 2,
      anon_sym_yes,
      anon_sym_no,
    STATE(16), 2,
      sym_number,
      sym_boolean,
    STATE(17), 5,
      sym_collection,
      sym_predicate,
      sym__value,
      sym_member,
      sym_literal,
  [97] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_id,
    ACTIONS(40), 1,
      sym_identifier,
    STATE(12), 1,
      sym__composite_definition,
    STATE(21), 1,
      sym__id_definition,
    STATE(28), 1,
      sym__primitive_definition,
    STATE(59), 1,
      sym_logical_operator,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_definition,
      aux_sym_content_file_repeat1,
    ACTIONS(43), 3,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [132] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_id,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym__composite_definition,
    STATE(21), 1,
      sym__id_definition,
    STATE(28), 1,
      sym__primitive_definition,
    STATE(59), 1,
      sym_logical_operator,
    STATE(4), 2,
      sym_definition,
      aux_sym_content_file_repeat1,
    ACTIONS(9), 3,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [166] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_id,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      sym__composite_definition,
    STATE(21), 1,
      sym__id_definition,
    STATE(28), 1,
      sym__primitive_definition,
    STATE(59), 1,
      sym_logical_operator,
    STATE(4), 2,
      sym_definition,
      aux_sym_content_file_repeat1,
    ACTIONS(9), 3,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [200] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_id,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym__composite_definition,
    STATE(21), 1,
      sym__id_definition,
    STATE(28), 1,
      sym__primitive_definition,
    STATE(59), 1,
      sym_logical_operator,
    STATE(5), 2,
      sym_definition,
      aux_sym_content_file_repeat1,
    ACTIONS(9), 3,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [234] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym_string,
    ACTIONS(19), 1,
      sym_decimal,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_integer,
    ACTIONS(17), 2,
      sym__positive_integer,
      sym__negative_integer,
    ACTIONS(54), 2,
      anon_sym_yes,
      anon_sym_no,
    STATE(9), 2,
      sym_literal,
      aux_sym_collection_repeat1,
    STATE(29), 2,
      sym_number,
      sym_boolean,
  [266] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    ACTIONS(58), 1,
      sym_string,
    ACTIONS(64), 1,
      sym_decimal,
    STATE(31), 1,
      sym_integer,
    ACTIONS(61), 2,
      sym__positive_integer,
      sym__negative_integer,
    ACTIONS(67), 2,
      anon_sym_yes,
      anon_sym_no,
    STATE(9), 2,
      sym_literal,
      aux_sym_collection_repeat1,
    STATE(29), 2,
      sym_number,
      sym_boolean,
  [298] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_DOT,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(72), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [316] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_DOT,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(78), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [334] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(82), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [349] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(86), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [364] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(90), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [379] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(94), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(98), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [409] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(102), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [424] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(106), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [439] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(110), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [454] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(115), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [469] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(120), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [484] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(124), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [499] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(128), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [514] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(132), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [529] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(136), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [544] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(140), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [559] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(78), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [574] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(120), 5,
      anon_sym_id,
      sym_identifier,
      anon_sym_NOT,
      anon_sym_NOR,
      anon_sym_OR,
  [589] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 2,
      sym__positive_integer,
      sym__negative_integer,
    ACTIONS(96), 5,
      anon_sym_RBRACE,
      sym_string,
      sym_decimal,
      anon_sym_yes,
      anon_sym_no,
  [604] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 2,
      sym__positive_integer,
      sym__negative_integer,
    ACTIONS(88), 5,
      anon_sym_RBRACE,
      sym_string,
      sym_decimal,
      anon_sym_yes,
      anon_sym_no,
  [619] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 2,
      sym__positive_integer,
      sym__negative_integer,
    ACTIONS(92), 5,
      anon_sym_RBRACE,
      sym_string,
      sym_decimal,
      anon_sym_yes,
      anon_sym_no,
  [634] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 2,
      sym__positive_integer,
      sym__negative_integer,
    ACTIONS(104), 5,
      anon_sym_RBRACE,
      sym_string,
      sym_decimal,
      anon_sym_yes,
      anon_sym_no,
  [649] = 5,
    ACTIONS(142), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    ACTIONS(146), 1,
      sym__localisation_string_content,
    ACTIONS(148), 1,
      anon_sym_DOLLAR,
    STATE(34), 2,
      sym_interpolation,
      aux_sym_localisation_string_repeat1,
  [666] = 5,
    ACTIONS(142), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_DQUOTE,
    ACTIONS(152), 1,
      sym__localisation_string_content,
    ACTIONS(155), 1,
      anon_sym_DOLLAR,
    STATE(34), 2,
      sym_interpolation,
      aux_sym_localisation_string_repeat1,
  [683] = 5,
    ACTIONS(142), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_DOLLAR,
    ACTIONS(158), 1,
      anon_sym_DQUOTE,
    ACTIONS(160), 1,
      sym__localisation_string_content,
    STATE(33), 2,
      sym_interpolation,
      aux_sym_localisation_string_repeat1,
  [700] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
    ACTIONS(164), 1,
      sym_identifier,
    STATE(36), 2,
      aux_sym__localisation_definitions,
      sym_localisation_definition,
  [714] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(169), 1,
      sym_identifier,
    STATE(36), 2,
      aux_sym__localisation_definitions,
      sym_localisation_definition,
  [728] = 2,
    ACTIONS(142), 1,
      sym_comment,
    ACTIONS(171), 3,
      anon_sym_DQUOTE,
      sym__localisation_string_content,
      anon_sym_DOLLAR,
  [737] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym__positive_integer,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_localisation_string,
  [750] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_identifier,
    STATE(37), 2,
      aux_sym__localisation_definitions,
      sym_localisation_definition,
  [761] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [769] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    STATE(45), 1,
      sym_localisation_string,
  [779] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_predicate,
  [789] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym__positive_integer,
    STATE(26), 1,
      sym_id_number,
  [799] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [807] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [815] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [823] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_identifier,
    STATE(13), 1,
      sym_id,
  [833] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      sym_identifier,
    STATE(27), 1,
      sym_member,
  [843] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_COLON,
  [850] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_EQ,
  [857] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_EQ,
  [864] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_EQ,
  [871] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_DOT,
  [878] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_identifier,
  [885] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_DOLLAR,
  [892] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
  [899] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_COLON,
  [906] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_EQ,
  [913] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
  [920] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 59,
  [SMALL_STATE(4)] = 97,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 166,
  [SMALL_STATE(7)] = 200,
  [SMALL_STATE(8)] = 234,
  [SMALL_STATE(9)] = 266,
  [SMALL_STATE(10)] = 298,
  [SMALL_STATE(11)] = 316,
  [SMALL_STATE(12)] = 334,
  [SMALL_STATE(13)] = 349,
  [SMALL_STATE(14)] = 364,
  [SMALL_STATE(15)] = 379,
  [SMALL_STATE(16)] = 394,
  [SMALL_STATE(17)] = 409,
  [SMALL_STATE(18)] = 424,
  [SMALL_STATE(19)] = 439,
  [SMALL_STATE(20)] = 454,
  [SMALL_STATE(21)] = 469,
  [SMALL_STATE(22)] = 484,
  [SMALL_STATE(23)] = 499,
  [SMALL_STATE(24)] = 514,
  [SMALL_STATE(25)] = 529,
  [SMALL_STATE(26)] = 544,
  [SMALL_STATE(27)] = 559,
  [SMALL_STATE(28)] = 574,
  [SMALL_STATE(29)] = 589,
  [SMALL_STATE(30)] = 604,
  [SMALL_STATE(31)] = 619,
  [SMALL_STATE(32)] = 634,
  [SMALL_STATE(33)] = 649,
  [SMALL_STATE(34)] = 666,
  [SMALL_STATE(35)] = 683,
  [SMALL_STATE(36)] = 700,
  [SMALL_STATE(37)] = 714,
  [SMALL_STATE(38)] = 728,
  [SMALL_STATE(39)] = 737,
  [SMALL_STATE(40)] = 750,
  [SMALL_STATE(41)] = 761,
  [SMALL_STATE(42)] = 769,
  [SMALL_STATE(43)] = 779,
  [SMALL_STATE(44)] = 789,
  [SMALL_STATE(45)] = 799,
  [SMALL_STATE(46)] = 807,
  [SMALL_STATE(47)] = 815,
  [SMALL_STATE(48)] = 823,
  [SMALL_STATE(49)] = 833,
  [SMALL_STATE(50)] = 843,
  [SMALL_STATE(51)] = 850,
  [SMALL_STATE(52)] = 857,
  [SMALL_STATE(53)] = 864,
  [SMALL_STATE(54)] = 871,
  [SMALL_STATE(55)] = 878,
  [SMALL_STATE(56)] = 885,
  [SMALL_STATE(57)] = 892,
  [SMALL_STATE(58)] = 899,
  [SMALL_STATE(59)] = 906,
  [SMALL_STATE(60)] = 913,
  [SMALL_STATE(61)] = 920,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_file_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_file, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_collection_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member, 3, 0, 6),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member, 3, 0, 6),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_definition, 1, 0, 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__id_definition, 3, 0, 3),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__id_definition, 3, 0, 3),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primitive_definition, 3, 0, 3),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primitive_definition, 3, 0, 3),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__composite_definition, 3, 0, 4),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__composite_definition, 3, 0, 4),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_collection, 2, 0, 0), REDUCE(sym_predicate, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_collection, 2, 0, 0), REDUCE(sym_predicate, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_definition, 1, 0, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_number, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id_number, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_collection, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_collection, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id, 3, 0, 5),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id, 3, 0, 5),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_localisation_string_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_localisation_string_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_localisation_string_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__localisation_definitions, 2, 0, 0),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__localisation_definitions, 2, 0, 0), SHIFT_REPEAT(50),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_language_localisation, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localisation_definition, 3, 0, 7),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localisation_definition, 4, 0, 8),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localisation_string, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localisation_string, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_operator, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localisation_file, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_witze(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "witze",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
